## PLAYBOOKS TO DELETE MULTIPLE ACCOUNTS
- hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Remove User Account
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
    with_items:
       - usseracount1
       - useraccount2

  - name: Remove users from sudoers file
    lineinfile:
      dest: /etc/sudoers
      backup: yes
      state: absent
      regexp: '{{ item }}\s'
      validate: 'visudo -cf %s'
    with_items:
       - useraccount1
       - useraccount2

  - name: Remove User from AllowGroup and AllowUsers in sshd config
    replace:
      regexp: "{{ item }}"
      backup: True
      path: /etc/ssh/sshd_config
      replace: "\b"
    with_items:
       - useraccount1
       - useraccount2     
