## PLAYBOOK TO DELETE SINGLE USER ACCOUNT
- hosts: webserver
  become: yes
  become_method: sudo

  tasks:
  - name: Remove User Account
    user:
      name: userchorus
      state: absent
      remove: yes

  - name: Remove a passwordless sudo entry in sudoers
    lineinfile:
      dest: /etc/sudoers
      backup: yes
      state: absent
      regexp: 'userchorus\s'
      validate: 'visudo -cf %s'

  - name: Remove User from AllowGroup and AllowUsers
    replace:
      regexp: "userchorus"
      backup: True
      path: /etc/ssh/sshd_config
      replace: "\b"

  - name: Restart ssh service
    service:
      name: sshd
      state: restarted
